### ISSUE TITLE
Configuration directory is called "epy", should be called "shirah-reader" or "shirah" instead

### ISSUE THREAD

**Issue by Saul-Dickson** [Hallicopter/shirah-reader#10]
### What's the problem?
Just as I said in the title, the problem is the name of the configuration directory. It's called `epy`, a name which makes no sense. The name of a configuration directory should always be the name of the program itself. Not a name the developer thought was creative or just used as a placeholder which the dev never changed. Why? Read the path in reverse. The "epy configuration directory," says that this directory is the configuration dir of the program `epy`. See what I'm saying yet?

### The solution:
This one is simple. Simply change the `prefix = os.path.join(homedir, ".config", "epy")` on line 836 of `shirah_reader/__main__.py` to `prefix = os.path.join(homedir, ".config", "shirah")` or `prefix = os.path.join(homedir, ".config", "shirah-reader")`, whichever one you like.

**Comment by Hallicopter** [comment]
Thanks, made a change.
