### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by ralyodio** [Hallicopter/shirah-reader#6]
I installed with pip3 but I get `command not found`

**Comment by Hallicopter** [comment]
Hi, you'd have to first install pip or pip3, which is the python package manager.

**Comment by aw-cloud** [comment]
Actually I think OP means it successfully installed, but the shirah command wasn't found. I had this 'issue' recently, as the binary was installed to somewhere like {$USER}/.local/bin which wasn't included in my PATH variable.

If this is the case, either explicitly reference the binary, add the path to PATH, or move/symlink etc. the binary to somewhere that is in your PATH.

**Comment by Hallicopter** [comment]
Closing this.
