### ISSUE TITLE
PDF support ?

### ISSUE THREAD

**Issue by Luc-Saccoccio** [Hallicopter/shirah-reader#7]
What about adding PDF support ?

**Comment by Hallicopter** [comment]
This will take a little longer, since pdf is a way more complicated format. Its sort of image-like sometimes, so can't extract text effectively without weird artifacts.

**Comment by Luc-Saccoccio** [comment]
Oh, okay. What about converting the PDF to a termporary ePub, and then read it ?

**Comment by Saul-Dickson** [comment]
PDF stands for Printable-Document-Format, and is, in fact, an image. It's encoding is pixel-based, not text-based, which makes "converting to temporary ePub" very difficult without using external tools, and errors would be plentiful, especially if the PDF includes pictures or backgrounds.

**Comment by Luc-Saccoccio** [comment]
I see, forget about it then

**Comment by ergpopler** [comment]
Hey! 
https://github.com/sgerwk/pdftoroff
This very quickly converts PDF's into Ebook format! 
If you want to read PDF books,
Just convert them.

Would be nice to have it integrated though.

**Comment by ergpopler** [comment]
something like: https://github.com/sgerwk/pdftoroff is easily able to pull text from PDF's

in fact, I was able to use it to convert a PDF to postscript, which i then converted into an ePub, perfect accuracy as far as i can see.
